### PR TITLE
fix: fix compatibility with vscode 1.74.0 and above

### LINKED ISSUE #28: Typing snippets are inserted in incorrect Position
Since latest [vscode update](https://code.visualstudio.com/updates/v1_75)(and previously vscode-insiders) I started experiencing typing snippets are inserted in incorrect Position. (this even made me use default `vscode` as I just can't write code  without this extension now)
Example:

https://user-images.githubusercontent.com/74474615/216970854-62b7c236-35ed-4eb4-a99f-1dc26ff9596e.mp4

Didn't dive into it but looks like smth has changed with the `editor.insertSnippet()` behaviour. Gonna propose quick solution in a minute

### PR DESCRIPTION
**Pull request by maIIady**
Looks like snippet location has to be adjusted to the inserting sequence lenght
Closes #28

### CODE REVIEW

**Comment by zardoy** [comment]
@maIIady so can you say why it is was failing and what changed in latest update (not necessary but would be interesting to know)? I only now that there were a lot of breakage from 2 last updates, so I'm still using November update and didn't experience such issues, so I'll test this change.

Also if I didn't do this already, can run prettier fix (because of prettier update)

**Review by zardoy — CHANGES_REQUESTED** [review]
1. It seems to be fixing typing snippets for vscode 1.74.0 and above, but lets also preserve support for versions below. we currently support >1.64.0, but its enought to test on 1.73.1. For this you can change version to test in `test/integration/runTests.ts` file.
2. - [X] @maIIady There seems other errors happening in new version, can you look and try to fix? I think they are super easy to fix (need to create new workspace edit instead of patching).

**Comment by zardoy** [comment]
@maIIady didn't you want to get this asap? I think I can help with getting it merged today

**Comment by maIIady** [comment]
I'd be grateful if you help with this (have no clue rn how to fix this)15:03, 17 February 2023, Vitaly ***@***.***>:
@maIIady didn't you want to get this asap? I think I can help with getting it merged today

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by zardoy** [comment]
Provided hack doesn't work (tests stil fail), I'll investigate it tomorrow

**Comment by zardoy** [comment]
@maIIady You could actually use `editor.selections.map(selection => selection.start.translate(undefined, -snippet.sequence.length))` to make all tests green, but hopefully I had a chance to investigate this. So this started happening because of range condition, they made extension host faster after that update and added a few more checks to let us know that we were doing things incorrectly (you could see error messages in console L)

**Pull request merged**
